project_id           = "your-gcp-project-id"
region               = "us-central1"
bucket_name          = "unique-name-for-your-bucket"
function_name        = "function-triggered-by-storage"
entry_point          = "your_function_entry_point"
function_source_path = "path/to/your/function-code.zip"
